# Generated by Django 5.0.2 on 2025-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.IntegerField(unique=True)),
                ('draw_date', models.DateField()),
                ('numbers', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('numbers', models.CharField(max_length=50)),
                ('model_type', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
